/// <reference types="@cloudflare/vitest-pool-workers/types" />

// The test env is the app's bindings (Cloudflare.Env, generated by
// `pnpm cf:typegen`) plus the test-only extras declared in
// vitest.config.ts. cloudflare:test types `env` as Cloudflare.Env, so we
// merge the extras into that namespace here.
declare namespace Cloudflare {
  interface Env {
    TEST_MIGRATIONS: import("cloudflare:test").D1Migration[];
  }
}
